package alwaysontime2;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.JFrame;

/**
 *
 * @author User
 */
public class showGraphPlot extends JFrame {

    private ArrayList<Vertex<Customer, Double>> vertices = new ArrayList<>();
    private ArrayList<Customer> totalRouteList = new ArrayList<>();
    private BufferedImage image;

    /**
     * Creates new form showGraphPlot
     */
    public showGraphPlot(ArrayList<Vertex<Customer, Double>> vertices, ArrayList<Customer> totalRouteList) {
        this.vertices = vertices;
        this.totalRouteList = totalRouteList;
        this.setTitle("Coordinates System");
        this.setSize(960, 960);
        this.setVisible(true);
        this.setResizable(true);
        this.setLayout(new BorderLayout());
    }

    public showGraphPlot() {
        initComponents();
    }

    public void paint(Graphics g) {
        super.paint(g);
//        Image img = new ImageIcon("download.png").getImage();
//        g.drawImage(img, 0, 0, null);
//        final BufferedImage image = ImageIO.read(new File("C:\\Projects\\MavenSandbox\\src\\main\\resources\\img.jpg"));
        int index = 0;
        Color[] arr = {Color.BLACK, Color.WHITE, Color.GREEN, Color.DARK_GRAY, Color.YELLOW, Color.PINK, Color.ORANGE, Color.WHITE};
        g.setColor(arr[index]);
        for (int i = 0; i < totalRouteList.size() - 1; i++) {
            if (!totalRouteList.get(i).equals(totalRouteList.get(i + 1))) {
                int startingXPoint = totalRouteList.get(i).getX() * 3;
                int startingYPoint = totalRouteList.get(i).getY() * 4;
                int endingXPoint = totalRouteList.get(i + 1).getX() * 3;
                int endingYPoint = totalRouteList.get(i + 1).getY() * 4;
                g.drawLine(startingXPoint, startingYPoint, endingXPoint, endingYPoint);
            } else {
                index++;
                g.setColor(arr[index % 7]);
            }
        }
        Font f = new Font("Comic Sans MS", Font.BOLD, 10);
        g.setFont(f);
        for (int i = 0; i < vertices.size(); i++) {
            int startingXPoint = vertices.get(i).vertexInfo.getX() * 3;
            int startingYPoint = vertices.get(i).vertexInfo.getY() * 4;
            if (i == 0) {
                g.setColor(Color.RED);
                g.fillOval(startingXPoint - 5, startingYPoint, 10, 10);
                g.drawString("DEPOT", startingXPoint + 7, startingYPoint + 10);
            } else {
                g.setColor(Color.BLUE);
                g.fillRect(startingXPoint - 5, startingYPoint, 10, 10);
                g.drawString("CUSTOMER " + i, startingXPoint + 7, startingYPoint + 10);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 960));
        setSize(new java.awt.Dimension(960, 960));
        getContentPane().setLayout(null);

        jLabel1.setText("Delivey Route");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 20, 70, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
